In [1]:
import numpy as np
import pandas as pd

**Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно**


In [16]:
a = np.linspace(12, 23, 12)
a

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

**Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.**

In [17]:
a1 = a.reshape (2, 6)
a2 = a.reshape (3, 4)
a3 = a.reshape (4, 3)
a4 = a.reshape (6, 2)
a5 = a.reshape (12, 1)

a1, a2, a3, a4, a5

(array([[12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.]]),
 array([[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]),
 array([[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.]]),
 array([[12., 13.],
        [14., 15.],
        [16., 17.],
        [18., 19.],
        [20., 21.],
        [22., 23.]]),
 array([[12.],
        [13.],
        [14.],
        [15.],
        [16.],
        [17.],
        [18.],
        [19.],
        [20.],
        [21.],
        [22.],
        [23.]]))

**Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?**

Нет, так как обращение к элементу все равно будет по 2м индексам (строка, столбец)

**Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального 
распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива 
одномерный массив с таким же атрибутом size, как и исходный массив.**


In [12]:
b = np.random.rand(3,4)
b

array([[0.86391726, 0.59774411, 0.20542455, 0.16566059],
       [0.74765546, 0.47243323, 0.07990208, 0.49916855],
       [0.03157649, 0.73166096, 0.20628825, 0.78845394]])

In [9]:
b1 = b.reshape(12)
b1

array([0.83229349, 0.78416273, 0.9255335 , 0.75452556, 0.25359465,
       0.79562402, 0.66950776, 0.72117954, 0.96888519, 0.26708726,
       0.65047757, 0.68433745])

**Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.**


In [15]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

**Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. 
В чем разница между массивами a и b?**


In [25]:
b = np.arange(20, 1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

не вижу разницы, может я не понял задание.

**Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше,
чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.**


In [51]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

**Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. 
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), 
состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. 
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. 
Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?**


In [36]:
a = np.arange(12)
A = a.reshape(4, 3)
At = A.T
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [38]:
B.size  # Размер матрицы

16

In [41]:
np.linalg.det(B)  # Обратную вычислить невозможно, данная матрица вырожденная

0.0

**Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.**

In [58]:
np.random.seed(42)

**Создайте одномерный массив c, составленный из последовательности 16-ти случайных 
равномерно распределенных целых чисел от 0 до 16 невключительно.**

In [83]:
c = np.random.randint(0, 16, (1, 16))
c

array([[ 2,  6, 11, 15,  9, 15,  8,  3, 11,  0,  1,  0, 15, 13, 11,  4]])

**Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, 
поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. 
Вычислите определитель, ранг и обратную матрицу D_inv для D.**


In [85]:
C = c.reshape(4, 4)
C

array([[ 2,  6, 11, 15],
       [ 9, 15,  8,  3],
       [11,  0,  1,  0],
       [15, 13, 11,  4]])

In [87]:
D = C*10 + B
D

array([[ 25,  74, 133, 182],
       [104, 200, 166, 152],
       [133,  86, 159, 212],
       [182, 252, 322, 342]])

In [89]:
np.linalg.det(D)

64109999.99999991

In [91]:
np.linalg.matrix_rank(D)

4

In [90]:
D_inv = np.linalg.inv(D)
D_inv

array([[-0.0104876 ,  0.00134768,  0.01066729, -0.00163032],
       [ 0.00746997,  0.01969272,  0.00404461, -0.01523475],
       [-0.01813009, -0.03338325, -0.02632101,  0.04080112],
       [ 0.01714678,  0.0162034 ,  0.01612479, -0.02339791]])

**Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. 
Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, 
используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, 
получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы 
D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, 
для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.**


In [98]:
D_inv = (D_inv > 0).astype(int)
D_inv

array([[0, 1, 1, 0],
       [1, 1, 1, 0],
       [0, 0, 0, 1],
       [1, 1, 1, 0]])

In [99]:
E = np.where(D_inv, B, C)
E

array([[  2,  14,  23,  15],
       [ 14,  50,  86,   3],
       [ 11,   0,   1, 212],
       [ 32, 122, 212,   4]])